name: simple workflow

on:
  workflow_dispatch: 

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "step 1 of job 1"
        name: step 1
        id: stepId
      - name: shellStep
        shell: python
        run: print("shell step 2")
        id: shellStep

      
      
