name: variables and secrets
on:
  workflow_dispatch: 
  push:

env:
  WF_VAR: "Workflow level variable"
jobs:
  test_variables_and_secrets:
    runs-on: ubuntu-latest
    name: job1
    env:
      JOB_VAR: "Job level variable"
    steps:
      - name: step1
        env:
          STEP_VAR: "Step level variable"
        run: |
          echo ${{ github.actor }}
          echo $GITHUB_JOB
          echo $WF_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo ${{ secrets.SEC_VAR }}
          echo ${{ vars.CONF_VAR }}
        
      
      
      
        
